cc=gcc
filename=create_childs
outputname=out
flags=-Wall -o

$(outputname): $(filename).c # generating $(outputname) requires $(filename).c and execution of below command
	$(cc) $(flags) $(outputname) $(filename).c
